
package com.baeldung.jaxws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BooksServiceImplService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:8080/booksservice?wsdl")
public class BooksServiceImplService
    extends Service
{

    private final static URL BOOKSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BOOKSSERVICEIMPLSERVICE_QNAME = new QName("http://ws/", "BooksServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/booksservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BOOKSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BooksServiceImplService() {
        super(__getWsdlLocation(), BOOKSSERVICEIMPLSERVICE_QNAME);
    }

    public BooksServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKSSERVICEIMPLSERVICE_QNAME, features);
    }

    public BooksServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BOOKSSERVICEIMPLSERVICE_QNAME);
    }

    public BooksServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKSSERVICEIMPLSERVICE_QNAME, features);
    }

    public BooksServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BooksServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BooksService
     */
    @WebEndpoint(name = "BooksServiceImplPort")
    public BooksService getBooksServiceImplPort() {
        return super.getPort(new QName("http://ws/", "BooksServiceImplPort"), BooksService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BooksService
     */
    @WebEndpoint(name = "BooksServiceImplPort")
    public BooksService getBooksServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BooksServiceImplPort"), BooksService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BOOKSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BOOKSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
