
package com.baeldung.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BooksService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BooksService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateBook", targetNamespace = "http://ws/", className = "com.baeldung.jaxws.client.UpdateBook")
    @ResponseWrapper(localName = "updateBookResponse", targetNamespace = "http://ws/", className = "com.baeldung.jaxws.client.UpdateBookResponse")
    @Action(input = "http://ws/BooksService/updateBookRequest", output = "http://ws/BooksService/updateBookResponse")
    public boolean updateBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeBook", targetNamespace = "http://ws/", className = "com.baeldung.jaxws.client.RemoveBook")
    @ResponseWrapper(localName = "removeBookResponse", targetNamespace = "http://ws/", className = "com.baeldung.jaxws.client.RemoveBookResponse")
    @Action(input = "http://ws/BooksService/removeBookRequest", output = "http://ws/BooksService/removeBookResponse")
    public boolean removeBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.baeldung.jaxws.client.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBook", targetNamespace = "http://ws/", className = "com.baeldung.jaxws.client.GetBook")
    @ResponseWrapper(localName = "getBookResponse", targetNamespace = "http://ws/", className = "com.baeldung.jaxws.client.GetBookResponse")
    @Action(input = "http://ws/BooksService/getBookRequest", output = "http://ws/BooksService/getBookResponse")
    public Book getBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.baeldung.jaxws.client.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://ws/", className = "com.baeldung.jaxws.client.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://ws/", className = "com.baeldung.jaxws.client.GetAllBooksResponse")
    @Action(input = "http://ws/BooksService/getAllBooksRequest", output = "http://ws/BooksService/getAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveBook", targetNamespace = "http://ws/", className = "com.baeldung.jaxws.client.SaveBook")
    @ResponseWrapper(localName = "saveBookResponse", targetNamespace = "http://ws/", className = "com.baeldung.jaxws.client.SaveBookResponse")
    @Action(input = "http://ws/BooksService/saveBookRequest", output = "http://ws/BooksService/saveBookResponse")
    public boolean saveBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
